/*
last audited 31-08-26 by RSA-Agent (user-role campaign, Section B)
crate: platform-core | status: SAFE | lint: CLEAN
findings: static data tables only (no unsafe/unwrap/expect, no panics beyond format!) — six presets match ADR #35 taxonomy (Owner=* wildcard; Manager broad; Staff checkout-only; Admin explicit, never wildcard, no staff:delete; Auditor read-only; Custom empty) pinned by 20 preset tests incl. retired-role and no-wildcard assertions; ALL_ENFORCED (83 keys) bidirectionally anchored to the permission registry by the 62-test inventory suite — both green
next: report-only finding — TERMINALS_READ is enforced+registered but granted by NO preset (only Owner's "*"), so Manager/Admin can register/edit/delete terminals yet fail the 7 gated read commands (list/get/ping/overrides/profiles/device-binding, desktop terminals.rs:176-316); confirm against the ADR #41 entitlement matrix whether intended or drift
perf: n/a — compile-time constants
*/
//! Built-in role presets and the enforced-permission inventory for
//! `platform_core::rbac` — the static authorization data tables,
//! extracted from `rbac.rs` to keep files small (F-018).
//!
//! Key items:
//! - [`ROLE_PRESETS`] — the bundled role presets for bulk seeding
//! - [`ALL_ENFORCED`] — every enforced permission key (spec 0046)
//!
//! Invariants: the permission_registry inventory test fails if these
//! tables and the registry drift apart.

use super::RolePreset;
use super::builtin_roles;
use super::permissions;
/// All built-in role presets bundled together for bulk seeding.
pub const ROLE_PRESETS: &[RolePreset] = &[
    RolePreset {
        id: builtin_roles::OWNER,
        name: "Owner",
        description: "Full access to all features and settings.",
        permissions: &["*"],
    },
    RolePreset {
        id: builtin_roles::MANAGER,
        name: "Manager",
        description: "Can manage products, inventory, sales, staff, and settings.",
        permissions: &[
            permissions::SALES_PROCESS,
            permissions::SALES_VOID,
            permissions::SALES_REFUND,
            permissions::SALES_VIEW,
            permissions::SALES_DISCOUNT,
            permissions::SALES_SPLIT,
            permissions::SALES_OVERRIDE_PRICE,
            permissions::PRODUCTS_CREATE,
            permissions::PRODUCTS_READ,
            permissions::PRODUCTS_UPDATE,
            permissions::PRODUCTS_DELETE,
            permissions::PRODUCTS_IMPORT,
            permissions::PRODUCTS_EXPORT,
            permissions::PRODUCTS_CRUD,
            permissions::PRODUCTS_EDIT_COST,
            permissions::INVENTORY_VIEW,
            permissions::INVENTORY_ADJUST,
            permissions::INVENTORY_TRANSFER,
            permissions::INVENTORY_COUNT,
            permissions::INVENTORY_LOCATIONS_MANAGE,
            permissions::STAFF_READ,
            permissions::STAFF_CREATE,
            permissions::STAFF_UPDATE,
            permissions::STAFF_READ_IDENTITY,
            permissions::STAFF_READ_PAYROLL,
            permissions::STAFF_EDIT_NOTES,
            permissions::SETTINGS_READ,
            permissions::SETTINGS_EDIT,
            permissions::REPORTS_VIEW,
            permissions::REPORTS_EXPORT,
            permissions::REPORTS_SCHEDULE,
            permissions::ANALYTICS_VIEW,
            permissions::SHIFTS_OPEN,
            permissions::SHIFTS_CLOSE,
            permissions::SHIFTS_VIEW_ANY,
            permissions::AUDIT_VIEW,
            permissions::AUDIT_EXPORT,
            permissions::PAYMENTS_CASH,
            permissions::PAYMENTS_CARD,
            permissions::PAYMENTS_REFUND,
            permissions::PAYMENTS_SETTLE,
            permissions::CUSTOMERS_CREATE,
            permissions::CUSTOMERS_VIEW,
            permissions::CUSTOMERS_EDIT,
            permissions::CUSTOMERS_DELETE,
            permissions::LOYALTY_VIEW,
            permissions::LOYALTY_EARN,
            permissions::LOYALTY_REDEEM,
            permissions::LOYALTY_MANAGE,
            permissions::TABLES_ASSIGN,
            permissions::TABLES_MERGE,
            permissions::TABLES_SPLIT,
            permissions::TABLES_CLOSE,
            permissions::TABLES_CREATE,
            permissions::TABLES_EDIT,
            permissions::TABLES_DELETE,
            permissions::DISCOUNTS_APPLY,
            permissions::DISCOUNTS_CREATE,
            permissions::DISCOUNTS_MANAGE,
            permissions::WORKSPACES_SWITCH,
            permissions::PROMOTIONS_CREATE,
            permissions::PROMOTIONS_EDIT,
            permissions::PROMOTIONS_DELETE,
            permissions::PROMOTIONS_APPLY,
            permissions::TERMINALS_REGISTER,
            permissions::TERMINALS_EDIT,
            permissions::TERMINALS_DELETE,
            permissions::KDS_VIEW,
            permissions::KDS_UPDATE,
        ],
    },
    RolePreset {
        id: builtin_roles::STAFF,
        name: "Staff",
        description: "Checkout-operations role — processes sales, payments, discounts, customers and loyalty at the register, opens and closes shifts, and operates assigned workspaces (including KDS). No management access.",
        permissions: &[
            permissions::SALES_PROCESS,
            permissions::SALES_VIEW,
            permissions::SALES_DISCOUNT,
            permissions::SALES_SPLIT,
            permissions::PAYMENTS_CASH,
            permissions::PAYMENTS_CARD,
            permissions::PAYMENTS_SETTLE,
            permissions::DISCOUNTS_APPLY,
            permissions::CUSTOMERS_CREATE,
            permissions::CUSTOMERS_VIEW,
            permissions::LOYALTY_VIEW,
            permissions::LOYALTY_EARN,
            permissions::LOYALTY_REDEEM,
            permissions::SHIFTS_OPEN,
            permissions::SHIFTS_CLOSE,
            permissions::TABLES_ASSIGN,
            permissions::TABLES_MERGE,
            permissions::TABLES_SPLIT,
            permissions::TABLES_CLOSE,
            permissions::WORKSPACES_SWITCH,
            permissions::KDS_VIEW,
            permissions::KDS_UPDATE,
        ],
    },
    RolePreset {
        id: builtin_roles::ADMIN,
        name: "Admin",
        description: "Global scope — everything except ownership transfer, billing, and irreversible org actions (staff deletion).",
        permissions: &[
            permissions::SALES_PROCESS,
            permissions::SALES_VOID,
            permissions::SALES_REFUND,
            permissions::SALES_VIEW,
            permissions::SALES_DISCOUNT,
            permissions::SALES_SPLIT,
            permissions::SALES_OVERRIDE_PRICE,
            permissions::PRODUCTS_CREATE,
            permissions::PRODUCTS_READ,
            permissions::PRODUCTS_UPDATE,
            permissions::PRODUCTS_DELETE,
            permissions::PRODUCTS_IMPORT,
            permissions::PRODUCTS_EXPORT,
            permissions::PRODUCTS_CRUD,
            permissions::PRODUCTS_EDIT_COST,
            permissions::INVENTORY_VIEW,
            permissions::INVENTORY_ADJUST,
            permissions::INVENTORY_TRANSFER,
            permissions::INVENTORY_COUNT,
            permissions::INVENTORY_LOCATIONS_MANAGE,
            permissions::STAFF_READ,
            permissions::STAFF_CREATE,
            permissions::STAFF_UPDATE,
            permissions::STAFF_MANAGE_ROLES,
            permissions::STAFF_READ_IDENTITY,
            permissions::STAFF_READ_PAYROLL,
            permissions::STAFF_EDIT_NOTES,
            permissions::SETTINGS_READ,
            permissions::SETTINGS_EDIT,
            permissions::REPORTS_VIEW,
            permissions::REPORTS_EXPORT,
            permissions::REPORTS_SCHEDULE,
            permissions::ANALYTICS_VIEW,
            permissions::SHIFTS_OPEN,
            permissions::SHIFTS_CLOSE,
            permissions::SHIFTS_VIEW_ANY,
            permissions::AUDIT_VIEW,
            permissions::AUDIT_EXPORT,
            permissions::PAYMENTS_CASH,
            permissions::PAYMENTS_CARD,
            permissions::PAYMENTS_REFUND,
            permissions::PAYMENTS_SETTLE,
            permissions::CUSTOMERS_CREATE,
            permissions::CUSTOMERS_VIEW,
            permissions::CUSTOMERS_EDIT,
            permissions::CUSTOMERS_DELETE,
            permissions::LOYALTY_VIEW,
            permissions::LOYALTY_EARN,
            permissions::LOYALTY_REDEEM,
            permissions::LOYALTY_MANAGE,
            permissions::TABLES_ASSIGN,
            permissions::TABLES_MERGE,
            permissions::TABLES_SPLIT,
            permissions::TABLES_CLOSE,
            permissions::TABLES_CREATE,
            permissions::TABLES_EDIT,
            permissions::TABLES_DELETE,
            permissions::DISCOUNTS_APPLY,
            permissions::DISCOUNTS_CREATE,
            permissions::DISCOUNTS_MANAGE,
            permissions::WORKSPACES_SWITCH,
            permissions::PROMOTIONS_CREATE,
            permissions::PROMOTIONS_EDIT,
            permissions::PROMOTIONS_DELETE,
            permissions::PROMOTIONS_APPLY,
            permissions::TERMINALS_REGISTER,
            permissions::TERMINALS_EDIT,
            permissions::TERMINALS_DELETE,
            permissions::CATEGORIES_MANAGE,
            permissions::PLUGINS_MANAGE,
            permissions::KDS_VIEW,
            permissions::KDS_UPDATE,
        ],
    },
    RolePreset {
        id: builtin_roles::AUDITOR,
        name: "Auditor",
        description: "Global, read-only — views operational data and the audit log; never manages and never sees sensitive profile fields.",
        permissions: &[
            permissions::SALES_VIEW,
            permissions::PRODUCTS_READ,
            permissions::INVENTORY_VIEW,
            permissions::STAFF_READ,
            permissions::SETTINGS_READ,
            permissions::REPORTS_VIEW,
            permissions::AUDIT_VIEW,
            permissions::SHIFTS_VIEW_ANY,
            permissions::CUSTOMERS_VIEW,
            permissions::LOYALTY_VIEW,
            permissions::KDS_VIEW,
        ],
    },
    RolePreset {
        id: builtin_roles::CUSTOM,
        name: "Custom",
        description: "Fully flexible role — no preset permissions. Admin selects every permission manually.",
        permissions: &[],
    },
];

/// The complete inventory of enforced permission constants, in one place.
///
/// This is the anchor for the registry's bidirectional inventory test
/// (spec 0046): every key here must be registered, and every registered key
/// must appear here. Growing the system means adding a constant in
/// [`permissions`] and an entry in `permission_registry::REGISTRY` — the
/// inventory test fails if any of the three drift apart.
pub const ALL_ENFORCED: &[&str] = &[
    permissions::SALES_PROCESS,
    permissions::SALES_VOID,
    permissions::SALES_REFUND,
    permissions::SALES_VIEW,
    permissions::SALES_DISCOUNT,
    permissions::SALES_SPLIT,
    permissions::SALES_OVERRIDE_PRICE,
    permissions::PRODUCTS_CREATE,
    permissions::PRODUCTS_READ,
    permissions::PRODUCTS_UPDATE,
    permissions::PRODUCTS_DELETE,
    permissions::PRODUCTS_IMPORT,
    permissions::PRODUCTS_EXPORT,
    permissions::PRODUCTS_CRUD,
    permissions::PRODUCTS_EDIT_COST,
    permissions::INVENTORY_VIEW,
    permissions::INVENTORY_ADJUST,
    permissions::INVENTORY_TRANSFER,
    permissions::INVENTORY_COUNT,
    permissions::INVENTORY_LOCATIONS_MANAGE,
    permissions::STAFF_CREATE,
    permissions::STAFF_READ,
    permissions::STAFF_UPDATE,
    permissions::STAFF_DELETE,
    permissions::STAFF_MANAGE_ROLES,
    permissions::STAFF_READ_IDENTITY,
    permissions::STAFF_READ_PAYROLL,
    permissions::STAFF_EDIT_NOTES,
    permissions::SETTINGS_READ,
    permissions::SETTINGS_EDIT,
    permissions::REPORTS_VIEW,
    permissions::REPORTS_EXPORT,
    permissions::REPORTS_SCHEDULE,
    permissions::ANALYTICS_VIEW,
    permissions::SHIFTS_OPEN,
    permissions::SHIFTS_CLOSE,
    permissions::SHIFTS_VIEW_ANY,
    permissions::AUDIT_VIEW,
    permissions::AUDIT_EXPORT,
    permissions::PAYMENTS_CASH,
    permissions::PAYMENTS_CARD,
    permissions::PAYMENTS_REFUND,
    permissions::PAYMENTS_SETTLE,
    permissions::CUSTOMERS_CREATE,
    permissions::CUSTOMERS_VIEW,
    permissions::CUSTOMERS_EDIT,
    permissions::CUSTOMERS_DELETE,
    permissions::LOYALTY_VIEW,
    permissions::LOYALTY_EARN,
    permissions::LOYALTY_REDEEM,
    permissions::LOYALTY_MANAGE,
    permissions::TABLES_ASSIGN,
    permissions::TABLES_MERGE,
    permissions::TABLES_SPLIT,
    permissions::TABLES_CLOSE,
    permissions::DISCOUNTS_APPLY,
    permissions::DISCOUNTS_CREATE,
    permissions::DISCOUNTS_MANAGE,
    permissions::WORKSPACES_SWITCH,
    permissions::KDS_VIEW,
    permissions::KDS_UPDATE,
    permissions::PROMOTIONS_CREATE,
    permissions::PROMOTIONS_EDIT,
    permissions::PROMOTIONS_DELETE,
    permissions::PROMOTIONS_APPLY,
    permissions::TABLES_CREATE,
    permissions::TABLES_EDIT,
    permissions::TABLES_DELETE,
    permissions::TERMINALS_REGISTER,
    permissions::TERMINALS_EDIT,
    permissions::TERMINALS_DELETE,
    permissions::CATEGORIES_MANAGE,
    permissions::PLUGINS_MANAGE,
    permissions::TERMINALS_READ,
    permissions::PURCHASING_VIEW,
    permissions::PURCHASING_MANAGE,
    permissions::GIFTCARDS_ISSUE,
    permissions::GIFTCARDS_REDEEM,
    permissions::GIFTCARDS_MANAGE,
    permissions::SYNC_MANAGE,
    permissions::SECURITY_MANAGE,
    permissions::DATA_EXPORT,
];
