// Internal-link audit of the built dist/ output — a FAILING gate on broken
// internal links. Run: node scripts/check-links.mjs (after `npm run build`;
// wired into CI as `npm run check:links`). Exits 1 when any broken link is
// found.
//
// Scope and skips (each deliberate):
//   • Only `href=` links on generated .html pages are checked. Fragments,
//     query strings, and external schemes (http/https, mailto:, tel:,
//     data:, javascript:, //-relative) are ignored.
//   • `${...}` in an href is a JS template-literal fragment — rustdoc's
//     search bundle emits `href="static.files/${f}"` inside inline scripts.
//     Never a real link; always skipped.
//   • Under `/docs-portal/api/rust/`, an href whose target has no file
//     extension and no trailing slash is rustdoc's rendering of an
//     unresolved intra-doc link (e.g. `href="crate::Span"`, `href="dispatcher#..."`)
//     — an identifier, not a file. Real rustdoc links always end in
//     `.html`. Scoped to the rustdoc tree so a bare-identifier link
//     anywhere else still fails.
//   • `\` in a URL is normalized to `/` (browsers treat them identically;
//     rustdoc built on Windows emits `src/...\module.rs.html` source links).
//   • The portal (`/docs-portal/`) is generated by third-party doc tools
//     (mdBook, rustdoc, TypeDoc). Two namespaces are excluded:
//       - `/docs-portal/assets/` — mdBook's print.html and TypeDoc's
//         depth-1 pages reference `assets/*` that the tools emit at other
//         paths (tool-template artifacts, not content links).
//       - the whole portal when `dist/docs-portal` is absent — the CI
//         check job does not build the portal (deploy does, soft-fail),
//         so portal links can only be validated when the portal is staged.
//     Everything else in the portal IS checked, so a hand-written guide
//     linking to a missing page still fails the gate.
//   • An href that ends in `/index.html` is valid when that file exists,
//     and its directory form (`/foo/` or `/foo`) is valid when
//     `/foo/index.html` exists — browsers serve both.
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, posix } from 'node:path';

const DIST = 'dist';
const PORTAL = '/docs-portal';
// Cap the printed list so a catastrophic break floods neither the terminal
// nor the CI log — the count is always printed in full.
const MAX_PRINTED = 100;

function walkAll(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walkAll(p, out);
    else out.push(p);
  }
  return out;
}

const toUrl = (p) => '/' + p.slice(DIST.length).replaceAll('\\', '/').replace(/^\/+/, '');

const all = walkAll(DIST);
const pages = all.filter((p) => p.endsWith('.html'));
const portalPresent = existsSync(join(DIST, 'docs-portal'));

// The set of every resolvable URL in dist/: the full URL of every file,
// plus the directory forms of every /index.html page.
const ok = new Set();
for (const p of all) {
  const url = toUrl(p);
  ok.add(url);
  if (p.endsWith('.html') && url.endsWith('/index.html')) {
    const dir = url.slice(0, -'index.html'.length); // keeps the trailing /
    ok.add(dir);
    ok.add(dir.replace(/\/$/, ''));
  }
}

const isExternal = (h) => /^(?:[a-z]+:)?\/\//i.test(h) || /^(?:mailto:|tel:|data:|javascript:)/i.test(h);
const isTemplateLiteral = (h) => h.includes('${');
const isGeneratedPortalAsset = (abs) => abs.startsWith(PORTAL + '/assets/');

const isRustdocIdentifierLink = (abs) =>
  abs.startsWith(PORTAL + '/api/rust/') && !abs.endsWith('/') && !/\.[^/]*$/.test(abs);
const isPortalLink = (abs) => abs === PORTAL || abs.startsWith(PORTAL + '/');

const broken = [];
for (const p of pages) {
  const html = readFileSync(p, 'utf8');
  const pageUrl = toUrl(p);
  const pageDir = posix.dirname(pageUrl) + '/'; // e.g. /en/docs/welcome/ -> /en/docs/welcome/
  const re = /href="([^"]+)"/g;
  let m;
  while ((m = re.exec(html))) {
    let h = m[1];
    if (h.startsWith('#') || isExternal(h) || isTemplateLiteral(h)) continue;
    h = h.split(/[#?]/)[0].replaceAll('\\', '/');
    if (!h) continue;
    const abs = h.startsWith('/')
      ? posix.normalize(h)
      : posix.normalize(posix.join(pageDir, h));
    if (abs === '/' || isGeneratedPortalAsset(abs) || isRustdocIdentifierLink(abs)) continue;
    // Portal links are only checkable when the portal is in this build.
    if (isPortalLink(abs) && !portalPresent) continue;
    if (!ok.has(abs) && !ok.has(abs.replace(/\/$/, ''))) {
      // mdBook's print.html flattens all pages to portal root; relative
      // links from subpages resolve incorrectly from print.html. Skip.
      if (pageUrl.endsWith('/docs-portal/print.html')) continue;
      broken.push(`${pageUrl} -> ${m[1]} (resolved ${abs})`);
    }
  }
}

console.log(
  `pages checked: ${pages.length} · files in dist: ${all.length} · portal staged: ${portalPresent ? 'yes' : 'no'}`,
);
if (broken.length) {
  console.log(`BROKEN INTERNAL LINKS: ${broken.length}`);
  for (const b of broken.slice(0, MAX_PRINTED)) console.log('  ' + b);
  if (broken.length > MAX_PRINTED) {
    console.log(`  …and ${broken.length - MAX_PRINTED} more (capped at ${MAX_PRINTED})`);
  }
  process.exitCode = 1;
} else {
  console.log('NO BROKEN INTERNAL LINKS');
}
