#!/usr/bin/env python3
"""Generate the Postgres DDL port of the SQLite schema migration.

Reads ``crates/oz-core/migrations/20260813_init.sql`` (the SQLite schema)
and writes ``crates/oz-core/migrations/20260813_init.pg.sql`` (Postgres DDL)
by applying the mapping the SQLite dialect needs to run on PostgreSQL:

* ``strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`` → ISO-8601 ``to_char(now() …)``
* ``datetime('now')`` → ``to_char(now() …)``
* ``INTEGER`` → ``BIGINT`` (SQLite INTEGER is 64-bit, like Rust ``i64``)
* ``REAL`` → ``DOUBLE PRECISION``
* ``INTEGER PRIMARY KEY AUTOINCREMENT`` → ``BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY``
* ``) STRICT;`` table option → dropped (Postgres has no equivalent)
* ``INSERT OR IGNORE`` → ``INSERT … ON CONFLICT DO NOTHING``
* the 4 SQLite triggers → ``plpgsql`` trigger functions + ``CREATE OR REPLACE TRIGGER``
* ``PRAGMA`` lines → dropped (foreign_keys is always on in Postgres)

Crucially, the CREATE TABLE statements are re-emitted in **topological
order**: SQLite permits a foreign key to reference a table defined later in
the file, but Postgres requires the referenced table to already exist. The
script parses each ``REFERENCES t(col)`` and Kahn-sorts the tables so the
DDL applies cleanly.

Usage:

    python3 scripts/generate-pg-migration.py

The generated file is idempotent (``IF NOT EXISTS`` / ``ON CONFLICT DO
NOTHING`` / ``CREATE OR REPLACE``) and is committed alongside this script so
``init.sql`` changes can be re-ported deterministically.
"""

from __future__ import annotations

import io
import re
from collections import defaultdict, deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# ── Row-Level Security: tenant isolation (PG-only appendix) ───────────────
#
# Every table carrying a tenant_id column gets RLS enabled with one
# `tenant_isolation` policy keyed on the `oz.tenant_id` session GUC.
#
# Behaviour:
#   * The table owner (today's app role) bypasses RLS, so nothing changes
#     until the deployment splits the app role from the owner (see
#     unify-auth-and-sync.md §11.5). FORCE ROW LEVEL SECURITY is deliberately
#     NOT set here — with no GUC in place it would break every query.
#   * Any NON-owner role is isolated immediately: without `oz.tenant_id`
#     set, current_setting(..., true) is NULL and the policy matches no
#     rows — reads return nothing and writes are rejected, so a missed
#     `WHERE tenant_id = ?` fails CLOSED instead of leaking.
#   * Cutover to enforcement: create a restricted app role, GRANT on the
#     tenant tables, set FORCE ROW LEVEL SECURITY, and have the app run
#     `SET LOCAL oz.tenant_id = <jwt tenant>` as the first statement of
#     every request transaction (reset on connection return).
RLS_SQL = """-- ── Row-Level Security: tenant isolation (PG-only) ─────────────────────
-- See the appendix source in scripts/generate-pg-migration.py.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY['bundle_items','offline_queue','product_activity',
                            'product_bundles','product_taxes','product_variants',
                            'products','sales','sent_reports','stripe_customers',
                            'sync_terminals','tax_rates','tenant_plans',
                            'tenant_subscription','users']
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE schemaname = 'public' AND tablename = t AND policyname = 'tenant_isolation'
        ) THEN
            EXECUTE format(
                'CREATE POLICY tenant_isolation ON %I
                 USING (tenant_id = current_setting(''oz.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''oz.tenant_id'', true))',
                t
            );
        END IF;
    END LOOP;
END $$;
"""
SRC = ROOT / "crates/oz-core/migrations/20260813_init.sql"
DST = ROOT / "crates/oz-core/migrations/20260813_init.pg.sql"

# ISO-8601 UTC timestamp string, matching SQLite's
# strftime('%Y-%m-%dT%H:%M:%fZ', 'now') output shape.
TS_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')"
# SQLite datetime('now') → 'YYYY-MM-DD HH:MM:SS'.
DT_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"

# Indexes that exist ONLY in the SQLite schema. PostgreSQL cannot build
# them: an expression index on a value derived from a TEXT column via a
# cast (`date(created_at)` / `created_at::date`) is rejected because the
# text→date cast is STABLE (DateStyle-dependent), not IMMUTABLE.
SQLITE_ONLY_INDEXES = {"idx_sales_status_created_date"}

HEADER = """\
-- ====================================================================
-- OZ-POS Database Schema — Postgres port of 20260813_init.sql
-- Generated by scripts/generate-pg-migration.py — DO NOT EDIT BY HAND.
-- Regenerate:  python3 scripts/generate-pg-migration.py
-- ====================================================================
"""

# Hand-written Postgres equivalents of the four SQLite triggers. Using
# CREATE OR REPLACE keeps the whole migration idempotent.
TRIGGERS_SQL = """\
-- audit_log immutability (SQLite triggers → plpgsql functions)
CREATE OR REPLACE FUNCTION audit_log_immutable_delete_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log entries are immutable: DELETE not allowed';
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_delete_fn();

CREATE OR REPLACE FUNCTION audit_log_immutable_update_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log entries are immutable: UPDATE not allowed';
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_update_fn();

-- loyalty_tiers validation (SQLite GLOB → Postgres regex)
CREATE OR REPLACE FUNCTION loyalty_tiers_validate_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF trim(NEW.name) = ''
       OR NEW.min_points < 0
       OR NEW.points_per_unit <= 0
       OR NEW.earn_multiplier <= 0
       OR length(NEW.colour) <> 7
       OR substr(NEW.colour, 1, 1) <> '#'
       OR NEW.colour !~ '^#[0-9A-Fa-f]{6}$'
    THEN
        RAISE EXCEPTION 'invalid loyalty tier configuration';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER loyalty_tiers_validate_insert
    BEFORE INSERT ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();

CREATE OR REPLACE TRIGGER loyalty_tiers_validate_update
    BEFORE UPDATE OF name, min_points, points_per_unit, earn_multiplier, colour
    ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();"""


def convert_table(stmt: str) -> str:
    """Apply the type/default mapping to a single CREATE TABLE statement."""
    s = stmt.replace("strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", TS_PG)
    s = s.replace("datetime('now')", DT_PG)
    s = s.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    s = re.sub(r"\bINTEGER\b", "BIGINT", s)
    s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s)
    # Drop the SQLite STRICT table option (no Postgres equivalent).
    s = re.sub(r"\s*STRICT(?=\s*;)", "", s)
    return s.rstrip()


def convert_seed(stmt: str) -> str:
    """Convert INSERT OR IGNORE to an idempotent Postgres upsert-ignore.

    The statement terminator is the first ``;`` after the INSERT keyword — a
    multi-row VALUES list never contains one — and the chunk may carry
    trailing comments after it, so ``endswith(";")`` cannot be relied on.
    """
    s = stmt.replace("INSERT OR IGNORE", "INSERT").rstrip()
    idx = s.find(";")
    if idx != -1:
        s = s[:idx].rstrip() + "\nON CONFLICT DO NOTHING;" + s[idx + 1 :]
    return s


def topo_sort(tables: list[tuple[str, set[str], str]]) -> list[tuple[str, set[str], str]]:
    """Kahn-sort tables so a referenced table is always created first."""
    by_name = {name: (name, refs, text) for name, refs, text in tables}
    names = [name for name, _, _ in tables]
    name_set = set(names)
    indegree = {n: 0 for n in names}
    adj: dict[str, list[str]] = defaultdict(list)
    for name, refs, _ in tables:
        for ref in refs:
            if ref in name_set and ref != name:
                adj[ref].append(name)
                indegree[name] += 1
    queue = deque(n for n in names if indegree[n] == 0)
    ordered: list[str] = []
    while queue:
        n = queue.popleft()
        ordered.append(n)
        for m in adj[n]:
            indegree[m] -= 1
            if indegree[m] == 0:
                queue.append(m)
    # A cycle should never happen; fall back to original order if it does.
    for n in names:
        if n not in ordered:
            ordered.append(n)
    return [by_name[n] for n in ordered]


def split_statements(text: str) -> list[str]:
    """Split on statement-start keywords, keeping each statement intact."""
    pattern = re.compile(
        r"(?m)^\s*(?:"
        r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS|"
        r"CREATE\s+TRIGGER\s+IF\s+NOT\s+EXISTS|"
        r"CREATE\s+(?:UNIQUE\s+)?INDEX\s+IF\s+NOT\s+EXISTS|"
        r"INSERT\s+OR\s+IGNORE|"
        r"PRAGMA"
        r")\b"
    )
    positions = [m.start() for m in pattern.finditer(text)]
    positions.append(len(text))
    return [text[positions[i] : positions[i + 1]] for i in range(len(positions) - 1)]


def main() -> None:
    text = io.open(SRC, encoding="utf-8", newline="").read().replace("\r\n", "\n")

    # Global timestamp mapping must also cover seed VALUES (workspace_instances).
    text = text.replace("strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", TS_PG)
    text = text.replace("datetime('now')", DT_PG)

    tables: list[tuple[str, set[str], str]] = []
    indexes: list[str] = []
    skipped_indexes: list[str] = []
    seeds: list[str] = []

    for stmt in split_statements(text):
        head = stmt.lstrip()
        if head.startswith("CREATE TABLE"):
            name = re.search(
                r'CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+"?(\w+)"?', head
            ).group(1)
            refs = set(re.findall(r'REFERENCES\s+"?(\w+)"?\s*\(', stmt))
            tables.append((name, refs, convert_table(stmt)))
        elif head.startswith("CREATE TRIGGER"):
            continue  # replaced by TRIGGERS_SQL
        elif head.startswith("CREATE INDEX") or head.startswith("CREATE UNIQUE INDEX"):
            name = re.search(r"idx_\w+|uq_\w+", head)
            if name and name.group(0) in SQLITE_ONLY_INDEXES:
                # PostgreSQL cannot index an expression derived from a TEXT
                # column via a cast (`date(created_at)` / `created_at::date`
                # are STABLE, DateStyle-dependent) — CREATE INDEX rejects
                # them as non-IMMUTABLE. The desktop analytics queries are
                # served by SQLite's `date()` expression index instead; the
                # PG report job remains a scan (fine for a background daily
                # job; see the plan doc).
                skipped_indexes.append(name.group(0))
                continue
            indexes.append(stmt.rstrip())
        elif head.startswith("INSERT OR IGNORE"):
            seeds.append(convert_seed(stmt))
        elif head.startswith("PRAGMA"):
            continue  # SQLite-only (foreign_keys / journal_mode)

    ordered = topo_sort(tables)

    out: list[str] = [HEADER.rstrip(), ""]
    for _name, _refs, stmt in ordered:
        out.extend([stmt, ""])
    out.extend([TRIGGERS_SQL, ""])
    for idx in indexes:
        out.extend([idx, ""])
    for seed in seeds:
        out.extend([seed, ""])
    out.extend([RLS_SQL, ""])

    # Match the sibling init.sql line endings (CRLF).
    body = "\n".join(out)
    body = body.replace("\n", "\r\n")
    io.open(DST, "w", encoding="utf-8", newline="").write(body)
    print(f"wrote {DST} ({len(ordered)} tables, {len(indexes)} indexes, {len(seeds)} seeds)")
    if skipped_indexes:
        print(
            "skipped PG-incompatible indexes (SQLite-only): "
            + ", ".join(sorted(skipped_indexes))
        )


if __name__ == "__main__":
    main()
