#!/usr/bin/env python3
"""Generate the Postgres port of the FULLY-MIGRATED SQLite schema.

Pipeline (rebuilt 2026-08-31; the old text-based version read only the
frozen 20260813_init.sql and silently diverged from the 14+ incremental
migrations — the drift the loyalty work exposed):

1. Parse the migration registry order from crates/oz-core/src/migrations.rs
   (the canonical source — registry order is NOT plain filename order).
2. Apply every migration to an in-memory SQLite database (python sqlite3,
   needs SQLite >= 3.35 for ALTER TABLE ... DROP COLUMN).
3. Dump the FINAL state: CREATE TABLE / index / trigger text from
   sqlite_master (SQLite keeps it current across ADD/DROP COLUMN), plus
   seed rows from every table that ends up non-empty.
4. Translate to Postgres DDL:

   * ``strftime('%Y-%m-%dT%H:%M:%fZ', 'now')`` → ISO-8601 ``to_char(now() …)``
   * ``datetime('now')`` → ``to_char(now() …)``
   * ``INTEGER`` → ``BIGINT`` (SQLite INTEGER is 64-bit, like Rust ``i64``)
   * ``REAL`` → ``DOUBLE PRECISION``
   * ``INTEGER PRIMARY KEY AUTOINCREMENT`` → ``BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY``
   * ``) STRICT`` table option → dropped (Postgres has no equivalent)
   * seeds → ``INSERT … ON CONFLICT DO NOTHING`` (idempotent re-apply);
     timestamp values that are "now"-derived (column DEFAULT or an
     explicit strftime in the seed INSERT — detected by freshness, see
     _quote) are re-emitted as the PG now-expression so output stays
     deterministic
   * triggers → hand-written plpgsql from TRIGGER_MAP; every dumped
     trigger needs an entry and every entry must be live (fail closed
     both ways — the ERR-10 stale-exemption discipline)
   * RLS appendix → curated RLS_TABLES list (enabling RLS is a policy
     decision: the write path must populate tenant_id); the generator
     fails if an entry loses its table or column, and lists tenant_id
     tables not yet covered as a visible comment

5. Re-emit CREATE TABLE in **topological order** (Kahn over
   ``REFERENCES t(col)``): SQLite tolerates forward FK references,
   Postgres does not.

Usage:

    python3 scripts/generate-pg-migration.py           # write the file
    python3 scripts/generate-pg-migration.py --check   # drift guard, writes nothing

--check renders the output twice (two independent migration runs) and
fails on any difference — that is the determinism self-proof — then
compares against the committed file (newline-normalized) and exits 1 on
drift without touching the working tree. CI runs --check; the pre-commit
hook runs it whenever a migration file or this script is staged.
"""

from __future__ import annotations

import re
import sqlite3
import sys
from collections import defaultdict, deque
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIG_DIR = ROOT / "crates" / "oz-core" / "migrations"
REGISTRY_RS = ROOT / "crates" / "oz-core" / "src" / "migrations.rs"
DST = MIG_DIR / "20260813_init.pg.sql"

# ISO-8601 UTC timestamp string, matching SQLite's
# strftime('%Y-%m-%dT%H:%M:%fZ', 'now') output shape.
TS_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"')"
# SQLite datetime('now') → 'YYYY-MM-DD HH:MM:SS'.
DT_PG = "to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')"

# Indexes that exist ONLY in the SQLite schema. PostgreSQL cannot build
# them: an expression index on a value derived from a TEXT column via a
# cast (`date(created_at)` / `created_at::date`) is rejected because the
# text→date cast is STABLE (DateStyle-dependent), not IMMUTABLE.
SQLITE_ONLY_INDEXES = {"idx_sales_status_created_date"}

HEADER = """\
-- ====================================================================
-- OZ-POS Database Schema — Postgres port of the fully-migrated SQLite
-- schema (20260813_init.sql + every incremental migration in the
-- crates/oz-core/src/migrations.rs registry, applied and dumped at
-- final state).
-- Generated by scripts/generate-pg-migration.py — DO NOT EDIT BY HAND.
-- Regenerate:  python3 scripts/generate-pg-migration.py
-- Drift guard: python3 scripts/generate-pg-migration.py --check
-- ====================================================================
"""

# Hand-written Postgres equivalents of the SQLite triggers, keyed by
# trigger name. The generator fails closed if the dumped set and this
# map ever disagree (missing port OR stale entry).
TRIGGER_MAP: dict[str, str] = {
    "audit_log_immutable_delete": """\
CREATE OR REPLACE FUNCTION audit_log_immutable_delete_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log entries are immutable: DELETE not allowed';
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_delete
    BEFORE DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_delete_fn();""",
    "audit_log_immutable_update": """\
CREATE OR REPLACE FUNCTION audit_log_immutable_update_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'audit_log entries are immutable: UPDATE not allowed';
END;
$$;

CREATE OR REPLACE TRIGGER audit_log_immutable_update
    BEFORE UPDATE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_immutable_update_fn();""",
    # loyalty_tiers validation (SQLite GLOB → Postgres regex). The
    # multiplier arm reads earn_multiplier_millionths — LOYALTY-01
    # replaced the REAL column with fixed-point integer millionths.
    "loyalty_tiers_validate_insert": """\
CREATE OR REPLACE FUNCTION loyalty_tiers_validate_fn() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF trim(NEW.name) = ''
       OR NEW.min_points < 0
       OR NEW.points_per_unit <= 0
       OR NEW.earn_multiplier_millionths <= 0
       OR length(NEW.colour) <> 7
       OR substr(NEW.colour, 1, 1) <> '#'
       OR NEW.colour !~ '^#[0-9A-Fa-f]{6}$'
    THEN
        RAISE EXCEPTION 'invalid loyalty tier configuration';
    END IF;
    RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER loyalty_tiers_validate_insert
    BEFORE INSERT ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();""",
    "loyalty_tiers_validate_update": """\
CREATE OR REPLACE TRIGGER loyalty_tiers_validate_update
    BEFORE UPDATE OF name, min_points, points_per_unit, earn_multiplier_millionths, colour
    ON loyalty_tiers
    FOR EACH ROW EXECUTE FUNCTION loyalty_tiers_validate_fn();""",
}

# Seed timestamps younger than this are "now"-derived (the migration run
# just stamped them) and re-emitted as the PG now-expression; older
# literals are fixed seed data and survive verbatim. 1 hour is orders of
# magnitude above any plausible build-vs-check gap while staying far
# below real seed dates.
NOW_FRESHNESS_SECONDS = 3600
ISO_RE = re.compile(r"^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}")


def registry_ids() -> list[str]:
    """Migration ids in canonical registry order (the Rust array order)."""
    text = REGISTRY_RS.read_text(encoding="utf-8")
    ids = re.findall(r'id:\s*"([^"]+\.sql)"', text)
    if not ids:
        raise SystemExit("error: could not parse any migration ids from migrations.rs")
    return ids


def build_db(ids: list[str]) -> sqlite3.Connection:
    db = sqlite3.connect(":memory:")
    for i in ids:
        sql = (MIG_DIR / i).read_text(encoding="utf-8")
        db.executescript(sql)
        db.commit()
    return db


def convert_table(stmt: str) -> str:
    """Apply the type/default mapping to a dumped CREATE TABLE statement."""
    s = stmt.replace("strftime('%Y-%m-%dT%H:%M:%fZ', 'now')", TS_PG)
    s = s.replace("datetime('now')", DT_PG)
    s = s.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    s = re.sub(r"\bINTEGER\b", "BIGINT", s)
    s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s)
    # Drop the SQLite STRICT table option (no Postgres equivalent).
    s = re.sub(r"\s+STRICT(?=\s*;?\s*$)", "", s)
    # sqlite_master stores the statement without IF NOT EXISTS even when
    # the migration used it; re-add for idempotent re-apply.
    s = re.sub(r"^CREATE TABLE (?!IF NOT EXISTS)", "CREATE TABLE IF NOT EXISTS ", s)
    return s.rstrip().rstrip(";") + ";"


def topo_sort(tables: list[tuple[str, set[str], str]]) -> list[tuple[str, set[str], str]]:
    """Kahn-sort tables so a referenced table is always created first."""
    by_name = {name: (name, refs, text) for name, refs, text in tables}
    names = [name for name, _, _ in tables]
    name_set = set(names)
    indegree = {n: 0 for n in names}
    adj: dict[str, list[str]] = defaultdict(list)
    for name, refs, _ in tables:
        for ref in refs:
            if ref in name_set and ref != name:
                adj[ref].append(name)
                indegree[name] += 1
    queue = deque(n for n in names if indegree[n] == 0)
    ordered: list[str] = []
    while queue:
        n = queue.popleft()
        ordered.append(n)
        for m in adj[n]:
            indegree[m] -= 1
            if indegree[m] == 0:
                queue.append(m)
    # A cycle should never happen; fall back to original order if it does.
    for n in names:
        if n not in ordered:
            ordered.append(n)
    return [by_name[n] for n in ordered]


def _quote(value: object) -> str:
    """SQL literal for a seed value, with the now-derived timestamp rule."""
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value) if isinstance(value, float) else str(value)
    if isinstance(value, bytes):
        raise SystemExit(f"error: BLOB seed data is not supported: {value[:16]!r}…")
    s = str(value)
    if ISO_RE.match(s):
        try:
            dt = datetime.fromisoformat(s.replace("Z", "+00:00").replace(" ", "T"))
            age = abs((dt - datetime.now(timezone.utc)).total_seconds())
            if age < NOW_FRESHNESS_SECONDS:
                return TS_PG
        except ValueError:
            pass
    return "'" + s.replace("'", "''") + "'"


def dump_seeds(db: sqlite3.Connection, ordered_tables: list[str]) -> list[str]:
    """One idempotent INSERT per non-empty table, in FK-topological order
    (seed tables reference each other: workspace_instances → workspace_types)."""
    out: list[str] = []
    for t in ordered_tables:
        cols = [c[1] for c in db.execute(f'PRAGMA table_info("{t}")')]
        rows = db.execute(f'SELECT * FROM "{t}" ORDER BY rowid').fetchall()
        if not rows:
            continue
        col_list = ", ".join(cols)
        values = ",\n    ".join(
            "(" + ", ".join(_quote(v) for v in row) + ")" for row in rows
        )
        out.append(
            f"INSERT INTO {t} ({col_list}) VALUES\n    {values}\n"
            "ON CONFLICT DO NOTHING;"
        )
    return out


def dump_rls(db: sqlite3.Connection) -> str:
    """RLS appendix over the CURATED RLS_TABLES list.

    Enabling RLS on a table is a policy decision, not a schema fact: the
    write path must set `tenant_id` on every INSERT or the policy's
    WITH CHECK rejects it (sale_lines is the cautionary example — it has
    the column but pg.rs inserts without it). So the list is curated,
    and the generator fails closed on staleness: every entry must exist
    in the final schema AND carry a tenant_id column. Tables that have
    tenant_id but are not yet covered are emitted as a visible comment
    block — the to-do list, never silently enabled.
    """
    final = {
        r[0]
        for r in db.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%'"
        )
    }
    tenant_tables = {
        t
        for t in final
        if any(
            c[1] == "tenant_id"
            for c in db.execute(f'PRAGMA table_info("{t}")')
        )
    }
    stale = [t for t in RLS_TABLES if t not in tenant_tables]
    if stale:
        raise SystemExit(
            "error: RLS_TABLES entries are no longer tenant tables "
            f"(dropped or lost tenant_id): {', '.join(stale)}"
        )
    uncovered = sorted(tenant_tables - set(RLS_TABLES))
    quoted = ",\n                            ".join(
        ", ".join(f"'{t}'" for t in chunk) for chunk in _chunks(sorted(RLS_TABLES), 6)
    )
    gap_comment = ""
    if uncovered:
        gap_comment = (
            "-- tenant_id tables NOT yet under RLS (write path must populate\n"
            "-- tenant_id before each can be added to RLS_TABLES):\n"
            + "".join(f"--   {t}\n" for t in uncovered)
            + "--\n"
        )
    return gap_comment + RLS_TEMPLATE.replace("__TABLES__", quoted)


# Curated RLS coverage — carried over from the hand-ported init.pg.sql
# (product_activity's tenant_id was PG-only hand-port fiction until the
# 20260831 rebuild migration added the real column on the SQLite side).
# Add a table here only after its REST/sync write path demonstrably sets
# tenant_id; the generator validates the entries.
RLS_TABLES = [
    "bundle_items",
    "edc_terminals",
    "media_assets",
    "media_thumbnails",
    "offline_queue",
    "payment_gateways",
    "payment_settlements",
    "product_activity",
    "product_bundles",
    "product_taxes",
    "product_variants",
    "products",
    "refunds",
    "sales",
    "sent_reports",
    "stripe_customers",
    "sync_terminals",
    "tax_rates",
    "tenant_plans",
    "tenant_subscription",
    "users",
]


def _chunks(items: list[str], size: int):
    for i in range(0, len(items), size):
        yield items[i : i + size]


RLS_TEMPLATE = """-- ── Row-Level Security: tenant isolation (PG-only) ─────────────────────
-- Curated coverage list (RLS_TABLES in scripts/generate-pg-migration.py);
-- the generator fails if an entry loses its tenant_id column or table.
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[__TABLES__]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        IF NOT EXISTS (
            SELECT 1 FROM pg_policies
            WHERE schemaname = 'public' AND tablename = t AND policyname = 'tenant_isolation'
        ) THEN
            EXECUTE format(
                'CREATE POLICY tenant_isolation ON %I
                 USING (tenant_id = current_setting(''oz.tenant_id'', true))
                 WITH CHECK (tenant_id = current_setting(''oz.tenant_id'', true))',
                t
            );
        END IF;
    END LOOP;
END $$;
"""


def render() -> str:
    ids = registry_ids()
    db = build_db(ids)

    tables: list[tuple[str, set[str], str]] = []
    for name, sql in db.execute(
        "SELECT name, sql FROM sqlite_master WHERE type='table' "
        "AND name NOT LIKE 'sqlite_%' ORDER BY rowid"
    ):
        refs = set(re.findall(r'REFERENCES\s+"?(\w+)"?\s*\(', sql))
        tables.append((name, refs, convert_table(sql)))
    ordered = topo_sort(tables)

    indexes: list[str] = []
    unique_by_table: dict[str, list[str]] = defaultdict(list)
    skipped: list[str] = []
    for name, tbl, sql in db.execute(
        "SELECT name, tbl_name, sql FROM sqlite_master WHERE type='index' "
        "AND sql IS NOT NULL ORDER BY name"
    ):
        if name in SQLITE_ONLY_INDEXES:
            skipped.append(name)
            continue
        s = re.sub(
            r"^CREATE (UNIQUE )?INDEX (?!IF NOT EXISTS)",
            r"CREATE \1INDEX IF NOT EXISTS ",
            sql,
        )
        s = s.rstrip().rstrip(";") + ";"
        # UNIQUE indexes must exist BEFORE any table whose FK references
        # their columns (composite FKs target them, and PG validates at
        # CREATE TABLE time) — emit each table's unique indexes directly
        # after that table in the topological loop.
        if s.upper().startswith("CREATE UNIQUE INDEX"):
            unique_by_table[tbl].append(s)
        else:
            indexes.append(s)

    dumped_triggers = [
        r[0]
        for r in db.execute(
            "SELECT name FROM sqlite_master WHERE type='trigger' ORDER BY name"
        )
    ]
    missing = [t for t in dumped_triggers if t not in TRIGGER_MAP]
    stale = [t for t in TRIGGER_MAP if t not in dumped_triggers]
    if missing or stale:
        parts = []
        if missing:
            parts.append(f"no plpgsql port: {', '.join(missing)}")
        if stale:
            parts.append(f"stale TRIGGER_MAP entries: {', '.join(stale)}")
        raise SystemExit("error: trigger parity broken — " + "; ".join(parts))

    seeds = dump_seeds(db, [name for name, _, _ in ordered])
    db.close()

    out: list[str] = [HEADER.rstrip(), ""]
    for name, _refs, stmt in ordered:
        out.extend([stmt, ""])
        for idx in unique_by_table.get(name, []):
            out.extend([idx, ""])
    for trig in sorted(TRIGGER_MAP):
        out.extend([TRIGGER_MAP[trig], ""])
    for idx in indexes:
        out.extend([idx, ""])
    for seed in seeds:
        out.extend([seed, ""])
    out.extend([dump_rls(build_db(ids)), ""])

    return "\n".join(out).replace("\n", "\r\n") + "\n", len(ordered), len(indexes), len(seeds), skipped


def main(argv: list[str]) -> int:
    check = "--check" in argv
    body, n_tables, n_indexes, n_seeds, skipped = render()

    # Determinism self-proof: a second independent migration run must
    # render byte-identical output (this is what makes --check honest).
    body2, *_ = render()
    if body != body2:
        print("error: generator output is not deterministic across runs", file=sys.stderr)
        return 1

    if check:
        committed = DST.read_text(encoding="utf-8").replace("\r\n", "\n")
        if committed == body.replace("\r\n", "\n"):
            print(f"ok: {DST.name} matches the generator ({n_tables} tables, "
                  f"{n_indexes} indexes, {n_seeds} seed inserts)")
            return 0
        gen_lines = body.replace("\r\n", "\n").splitlines()
        com_lines = committed.splitlines()
        diff = sum(1 for a, b in zip(gen_lines, com_lines) if a != b)
        diff += abs(len(gen_lines) - len(com_lines))
        print(
            f"error: {DST.name} has drifted from the generator ({diff} differing "
            "lines; generated is authoritative). Never hand-edit the PG file — "
            "run: python3 scripts/generate-pg-migration.py\n"
            "If the drift is in a trigger, port the plpgsql in TRIGGER_MAP first.",
            file=sys.stderr,
        )
        return 1

    DST.write_text(body, encoding="utf-8", newline="")
    print(f"wrote {DST} ({n_tables} tables, {n_indexes} indexes, {n_seeds} seed inserts)")
    if skipped:
        print("skipped PG-incompatible indexes (SQLite-only): " + ", ".join(sorted(skipped)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
