#!/usr/bin/env bash
# scripts/verify-docker-all.sh — comprehensive Docker-sector verification gate.
#
# Runs the full audit/26 Docker verification surface in one command:
#
#   1. Persistence   (DOCKER-11)  — delegates to verify-docker-persistence.sh:
#      cloud SQLite + license PocketBase both survive a full container
#      replacement on named volumes (boot → write → replace → assert).
#   2. Digest drift  (DOCKER-12)  — delegates to verify-docker-digests.sh:
#      every pinned `image:tag@sha256:...` reference is re-resolved and must
#      still match (fail-closed on unresolvable pins).
#   3. Log rotation  (DOCKER-13)  — every service in EVERY compose merge
#      combo (base, +prod, +pg, +prod+pg) must render the json-file
#      `max-size: "10m"` / `max-file: "5"` logging block.
#   4. OZ_DB_PATH guard (DOCKER-15) — a Windows-style OZ_DB_PATH must be
#      rejected at startup with the actionable MSYS_NO_PATHCONV=1 hint.
#
# Usage:
#   OZ_LICENSE_PRIVATE_KEY="$(cat crates/oz-core/oz-license-private.pem)" \
#     bash scripts/verify-docker-all.sh
#
# A throwaway RSA key is generated by the persistence delegate when
# OZ_LICENSE_PRIVATE_KEY is unset. Compose secrets are supplied as dummy
# non-empty values for the config-render checks.
#
# Requires a Docker daemon with BuildKit (docker buildx imagetools).
# Exit 0 = all checks passed. Exit 1 = at least one check failed.

set -euo pipefail
cd "$(dirname "$0")/.."

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'
pass() { printf "${GREEN}✔ %s${NC}\n" "$1"; }
fail() { printf "${RED}✘ %s${NC}\n" "$1"; }

overall=0

echo "═══ OZ-POS Docker verification gate (audit/26) ═══"

# ═══════════════════════════════════════════════════════════════════
# 1/4 — Persistence (DOCKER-11)
# ═══════════════════════════════════════════════════════════════════
echo
echo "── 1/4 Persistence (cloud SQLite + license PocketBase) ──"
if bash scripts/verify-docker-persistence.sh; then
    pass "persistence: both images survive container replacement"
else
    fail "persistence gate failed"
    overall=1
fi

# ═══════════════════════════════════════════════════════════════════
# 2/4 — Digest drift (DOCKER-12)
# ═══════════════════════════════════════════════════════════════════
echo
echo "── 2/4 Digest drift (pinned image references) ──"
if bash scripts/verify-docker-digests.sh; then
    pass "digests: all pinned image references are current"
else
    fail "digest-drift gate failed"
    overall=1
fi

# ═══════════════════════════════════════════════════════════════════
# 3/4 — Log rotation config (DOCKER-13)
# ═══════════════════════════════════════════════════════════════════
echo
echo "── 3/4 Log rotation (json-file max-size/max-file in every merge combo) ──"

# Compose fails closed on secrets; supply non-empty placeholders so the
# config render (not a real deploy) succeeds. MSYS_NO_PATHCONV is
# unnecessary here — compose reads env vars directly, never the shell argv.
export OZ_API_SECRET="${OZ_API_SECRET:-rotation-check-secret}"
export OZ_LICENSE_PRIVATE_KEY="${OZ_LICENSE_PRIVATE_KEY:-rotation-check-key}"
export PG_PASSWORD="${PG_PASSWORD:-rotation-check-pg}"

rotation_failed=0
combos=(
    "docker-compose.yml"
    "docker-compose.yml docker-compose.prod.yml"
    "docker-compose.yml docker-compose.pg.yml"
    "docker-compose.yml docker-compose.prod.yml docker-compose.pg.yml"
)
for combo in "${combos[@]}"; do
    # NOTE: build `-f <file>` pairs as separate array elements — composing
    # them into one string (`args[$i]="-f ${args[$i]}"`) makes docker
    # compose treat "-f docker-compose.yml" as a single mangled argument.
    args=()
    for f in $combo; do args+=(-f "$f"); done
    cfg=$(docker compose "${args[@]}" config 2>&1 || true)
    if [ -z "$cfg" ]; then
        echo "  ✘ $combo → docker compose config failed:"
        docker compose "${args[@]}" config 2>&1 | tail -3 | sed 's/^/    /'
        rotation_failed=1
        continue
    fi
    # Compare against the ACTUAL per-combo service count so a service added
    # without rotation can't slip past a loose threshold.
    total=$(docker compose "${args[@]}" config --services 2>/dev/null | wc -l)
    services=$(echo "$cfg" | grep -c "max-size: 10m" || true)
    if [ "$services" -eq "$total" ]; then
        echo "  ✔ $combo → $services/$total service(s) with log rotation"
    else
        echo "  ✘ $combo → only $services/$total service(s) with max-size"
        rotation_failed=1
    fi
done
if [ "$rotation_failed" -ne 0 ]; then
    fail "log-rotation config missing in at least one merge combo"
    overall=1
else
    pass "log rotation configured on all services in all merge combos"
fi

# ═══════════════════════════════════════════════════════════════════
# 4/4 — OZ_DB_PATH Windows-path guard (DOCKER-15)
# ═══════════════════════════════════════════════════════════════════
echo
echo "── 4/4 OZ_DB_PATH Windows-path guard ──"

# Reuse the cloud image the persistence delegate just built; if it was
# skipped or the tag differs, build it here so the check is self-contained.
CLOUD_IMG="oz-pos-cloud:persist-verify"
if ! docker image inspect "$CLOUD_IMG" >/dev/null 2>&1; then
    echo "  (building cloud image for the guard check…)"
    docker build -q -f Dockerfile.server -t "$CLOUD_IMG" . >/dev/null
fi

# The exact mangled form seen in the field (Git Bash path conversion).
# `timeout` guards against a regression where the server starts instead of
# rejecting the path — that would otherwise hang the gate on a foreground
# `docker run`. Exit 124 (timeout) is treated as an explicit failure.
out=$(MSYS_NO_PATHCONV=1 timeout 60 docker run --rm \
    -e OZ_DB_PATH='C:/Users/User/AppData/Local/Temp/test.db' \
    "$CLOUD_IMG" 2>&1 || true)
if echo "$out" | grep -q "looks like a Windows path" \
   && echo "$out" | grep -q "MSYS_NO_PATHCONV=1"; then
    pass "Windows-style OZ_DB_PATH rejected with actionable MSYS_NO_PATHCONV=1 hint"
else
    echo "  unexpected output:"
    echo "$out" | tail -5
    fail "OZ_DB_PATH guard did not fire (timeout = server started instead of rejecting)"
    overall=1
fi

# ═══════════════════════════════════════════════════════════════════
# Summary
# ═══════════════════════════════════════════════════════════════════
echo
if [ "$overall" -eq 0 ]; then
    printf "${GREEN}✔ ALL DOCKER CHECKS PASSED — persistence, digests, log rotation, OZ_DB_PATH guard.${NC}\n"
else
    printf "${RED}✘ DOCKER CHECKS FAILED — see messages above.${NC}\n"
fi
exit "$overall"
