-- 118_drop_warehouse_id_superseded.sql
-- Supersession cleanup: drop the ADR #4 Phase 2 `warehouse_id` columns.
--
-- Migration 069 added `warehouse_id` to inventory and stock_counts as a
-- speculative "multi-warehouse routing (future enhancement)" hook. That
-- enhancement never landed — and the concept was superseded before it
-- could, by ADR #18's first-class location catalog:
--
--   1. Migration 078 creates `inventory_locations` with
--      `type CHECK (... 'warehouse' ...)` — a warehouse is now just an
--      inventory_locations row with type = 'warehouse' (and the
--      workspace binding framework in 082/083 operates on locations).
--   2. Migration 079 adds `inventory.location_id` FK → inventory_locations
--      — the real location link. Its header states verbatim that the
--      ADD COLUMN form was chosen instead of a rebuild precisely to keep
--      migration_069's warehouse_id assertions green, not because the
--      column carried meaning: "Migration 069 already added a
--      `warehouse_id` column. The rebuild form would either drop or
--      rename it, breaking the existing tests."
--   3. The design decision (docs/decisions/2026-07-10-workspace-type-
--      instance-design.md) explicitly rejects warehouse scoping:
--      "No data scoping — no store_id or warehouse_id filter."
--
-- Zero Rust code reads or writes `warehouse_id` (verified across the
-- workspace — the only references are this column's own migration files
-- and the registry test assertions). Migration 113 carried the column
-- forward through the stock_counts rebuild as a faithful copy, and the
-- `idx_inventory_warehouse_product` index exists for a predicate no
-- query ever issues. Keeping dead schema invites drift — a future writer
-- could populate warehouse_id believing it is the location link, creating
-- a second, conflicting location identity alongside location_id.
--
-- This migration therefore DROPS the superseded columns and their dead
-- index. The store_id scoping columns from 069 are NOT touched — they are
-- the active ADR #4 layer, hardened by migration 117's FK.
--
-- DATA NOTE: any pre-existing warehouse_id VALUE is intentionally
-- discarded, never copied to location_id. warehouse_id was never a
-- location link (its values, e.g. 'wh-A', are not inventory_locations
-- UUIDs), so remapping them to location_id would corrupt the location
-- catalog FK. No code writes the column (always NULL in practice), and
-- every other column's data is preserved verbatim by DROP COLUMN —
-- pinned by migration_118_drop_preserves_inventory_and_count_data_on_upgrade.
--
-- SQLite refuses to drop a column that is indexed, so the index on
-- inventory.warehouse_id must be dropped first. stock_counts.warehouse_id
-- carries no index and drops directly. DROP COLUMN rewrites the table and
-- preserves every other column's data; the runner's DB-05 FK isolation is
-- not required (neither column is a foreign key), but the migration is
-- safe under both enforcement modes.

DROP INDEX IF EXISTS idx_inventory_warehouse_product;

ALTER TABLE inventory DROP COLUMN warehouse_id;
ALTER TABLE stock_counts DROP COLUMN warehouse_id;
