import { describe, expect, it } from 'vitest';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { pairingAdmitsKinds } from '@/features/stores/topologyCard';
import topologySemantics from '@/features/stores/topologySemantics.json';

// ADR #45 §2 — the cross-language corpus.
//
// `crates/oz-core/src/topologySemantics.matrix.json` is the full
// (pairing row × source kind × target kind) verdict table, generated by the
// RUST evaluator. This suite re-derives every one of those verdicts with the
// TYPESCRIPT evaluator and requires them to match.
//
// That is the check the byte-parity guard could never make: it proved the two
// sides read the same contract file, not that they compute the same answer from
// it. The failure mode it retires is the one recorded in CHANGELOG.md:144 —
// same JSON, two hand-written rule sets, and a merchant finding the
// disagreement at Apply.
//
// A mismatch here means one of two things, and both are deliberate acts:
//   - the frontend gate drifted from the backend → fix the frontend;
//   - the contract changed on purpose → regenerate the golden
//     (TOPOLOGY_MATRIX_UPDATE=1 cargo test -p oz-core --lib topology_matrix)
//     and review the matrix diff, which is where the new rule gets argued.

const MATRIX_PATH = resolve(
  __dirname,
  '../../../crates/oz-core/src/topologySemantics.matrix.json',
);

interface MatrixFixture {
  generatedBy: string;
  contractSchemaVersion: number;
  kinds: string[];
  rows: Array<{
    source: string;
    target: string;
    relationshipType: string;
    verdicts: Record<string, boolean>;
  }>;
}

function loadMatrix(): MatrixFixture {
  let raw: string;
  try {
    raw = readFileSync(MATRIX_PATH, 'utf-8');
  } catch {
    throw new Error(
      `topology matrix golden missing at ${MATRIX_PATH} — regenerate with `
      + 'TOPOLOGY_MATRIX_UPDATE=1 cargo test -p oz-core --lib topology_matrix',
    );
  }
  return JSON.parse(raw) as MatrixFixture;
}

const matrix = loadMatrix();

describe('topology corpus matrix (ADR #45 §2) — the TypeScript gate vs the Rust golden', () => {
  it('records the same contract schema version the UI reads', () => {
    expect(matrix.contractSchemaVersion).toBe(topologySemantics.schemaVersion);
  });

  it('holds exactly one row per declared pairing, in contract order', () => {
    expect(matrix.rows.map((row) => `${row.source}|${row.target}|${row.relationshipType}`)).toEqual(
      topologySemantics.semanticPairings.map(
        (row) => `${row.source}|${row.target}|${row.relationshipType}`,
      ),
    );
  });

  it('probes every kind the contract declares', () => {
    for (const key of topologySemantics.endpointWorkspaceTypeKeys) {
      expect(matrix.kinds).toContain(`workspace:${key}`);
    }
    for (const kind of topologySemantics.nodeKinds) {
      // `workspace` is probed through its family members, which the contract
      // enumerates above; the other node kinds are probed directly.
      if (kind === 'workspace') continue;
      expect(matrix.kinds).toContain(kind);
    }
  });

  // The heart of the slice: every verdict, both ways. 7 rows × 9 × 9 kinds.
  it.each(matrix.rows.flatMap((row) => (
    matrix.kinds.flatMap((from) => (
      matrix.kinds.map((to) => [row.source, row.target, from, to] as const)
    ))
  )))('pairingAdmitsKinds(%s, %s, %s, %s) matches the Rust evaluator', (
    source,
    target,
    from,
    to,
  ) => {
    const row = matrix.rows.find((r) => r.source === source && r.target === target);
    expect(row, `golden row ${source}→${target} is missing`).toBeDefined();
    expect(row!.verdicts[`${from}|${to}`], `golden verdict for ${from}→${to} is missing`)
      .toStrictEqual(pairingAdmitsKinds(source, target, from, to));
  });

  it('agrees with the golden on the fail-closed probes', () => {
    // Pinned separately from the generated sweep because these three are the
    // ones a future refactor is most likely to loosen by accident: an
    // unregistered workspace type, a purpose_key mistaken for a type_key, and
    // a kind that exists in no vocabulary at all.
    expect(pairingAdmitsKinds('stock-out', 'stock-in', 'workspace:pharmacy-pos', 'warehouse')).toBe(false);
    expect(pairingAdmitsKinds('stock-out', 'stock-in', 'workspace:general', 'warehouse')).toBe(false);
    expect(pairingAdmitsKinds('ticket-out', 'ticket-in', 'not-a-kind', 'hardware')).toBe(false);
  });

  it('agrees with the golden on the merchant-visible rule the contract exists to state', () => {
    // The four relationships a real branch can actually author today, asserted
    // by name so a green sweep cannot hide a wholesale flip of the table.
    expect(pairingAdmitsKinds('location-out', 'location-in', 'branch-location', 'workspace:kds')).toBe(true);
    expect(pairingAdmitsKinds('operation-out', 'operation-in', 'workspace:restaurant-pos', 'workspace:kds')).toBe(true);
    expect(pairingAdmitsKinds('ticket-out', 'ticket-in', 'workspace:kds', 'hardware')).toBe(true);
    expect(pairingAdmitsKinds('device-out', 'generic-in', 'hardware', 'hardware')).toBe(true);
    // And the one the canvas used to offer while the backend rejected it.
    expect(pairingAdmitsKinds('operation-out', 'operation-in', 'hardware', 'warehouse')).toBe(false);
  });
});
